# Generated by Django 3.2.6 on 2024-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lend',
            name='organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lend',
            name='person_picking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lend',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lend',
            name='picking',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lend',
            name='returning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
